{% set name = "textattack" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QData/{{ name|title }}/archive/v{{ version }}.tar.gz
  sha256: 1220a93ab76911cd29b600f44dbab904933fd5b5991277a8b4b0c2038bf57f1e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -v

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bert_score
    - editdistance
    - filelock
    - language_tool_python
    - lru-dict
    # - nlp
    - numpy <1.19.0
    - pandas
    # - scikit-learn
    - scipy
    - pytorch
    # - sentence-transformers
    - transformers
    # - tensorflow
    # - tensorflow-hub
    # - tensorboardX
    - terminaltables
    # - torchfile
    - tokenizers
    - tqdm
    - visdom
    # - wandb
    - python-flair
    - more-itertools
    - lemminflect
    - num2words
    - word2number
    - datasets
    - nltk

test:
  commands:
    - textattack --help

about:
  home: https://github.com/QData/textattack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generating adversarial examples for NLP models
  doc_url: https://textattack.readthedocs.io/en/latest/
  dev_url: https://github.com/QData/textattack

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
