{% set name = "textattack" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QData/TextAttack/archive/v{{ version }}.tar.gz
  sha256: 4b593286f06af0ed1c54787f7486600670e99caa140b7f327f329bba30eedeb8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6,<3.8
    - pip
  run:
    - python >=3.6,<3.8
    - bert_score
    - editdistance
    - filelock
    - language_tool_python
    - lru-dict
    - nlp
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - pytorch
    - transformers
    - tensorflow
    - tensorflow-hub
    - tensorboardX
    - terminaltables
    - torchfile
    - tokenizers
    - tqdm
    - visdom
    - wandb
    - python-flair
    - lemminflect
    - num2words
    - word2number
    - datasets
    - nltk

test:
  imports:
    - textattack

about:
  home: https://github.com/QData/textattack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generating adversarial examples for NLP models
  doc_url: https://textattack.readthedocs.io/en/latest/
  dev_url: https://github.com/QData/textattack

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
