{% set name = "textattack" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QData/{{ name|title }}/archive/v{{ version }}.tar.gz
  sha256: 82071b49da645c13e4666fb5da6aab08d5ec0f6d0b3d95c806739a294771ec46
  
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bert_score >=0.3.5
    - datasets
    - editdistance
    - filelock
    - python-flair
    - language_tool_python
    - lemminflect
    - lru-dict
    - more-itertools
    - nltk
    - num2words
    - numpy >=1.19.2
    - pandas >=1.0.1
    - pysocks !=1.5.7,>=1.5.6
    - python >=3.6
    - scipy >=1.4.1
    - terminaltables
    - pytorch !=1.8,>=1.7.0
    - tqdm <4.50.0,>=4.27
    - transformers >=3.3.0
    - word2number
    - huggingface-hub

test:
  imports:
    - textattack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QData/textattack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generating adversarial examples for NLP models
  doc_url: https://textattack.readthedocs.io/en/latest/
  dev_url: https://github.com/QData/textattack

extra:
  recipe-maintainers:
    - mxr-conda
